server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**, 
        - id: delivery-service
          uri: http://localhost:8083
          predicates:
            - Path=/deliveries/**, 
        - id: customer-service
          uri: http://localhost:8084
          predicates:
            - Path=/customerSupports/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://orderService:8080
          predicates:
            - Path=/orders/**, 
        - id: delivery-service
          uri: http://deliveryService:8080
          predicates:
            - Path=/deliveries/**, 
        - id: customer-service
          uri: http://customerService:8080
          predicates:
            - Path=/customerSupports/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
